/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafikak2;

import javax.swing.JOptionPane;

/**
 *
 * @author honzik
 */
public class EditPictureFrame extends javax.swing.JFrame {

    ImageLookupTable ilut;
    PpmPanel imagePanel;
    ImageTransform imgTransform;
    int previousSliderValue;

    /**
     * Creates new form EditPictureFrame
     */
    public EditPictureFrame(PpmPanel imagePanel) {
        initComponents();
        ilut = new ImageLookupTable(imagePanel);
        this.imagePanel = imagePanel;
        imgTransform = new ImageTransform(this.imagePanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        rValueTb = new javax.swing.JTextField();
        bValueTb = new javax.swing.JTextField();
        gValueTb = new javax.swing.JTextField();
        addRgbValueButton = new javax.swing.JButton();
        subtractRgbValueButton = new javax.swing.JButton();
        multiplyRgbValueButton = new javax.swing.JButton();
        divideRgbValueButton = new javax.swing.JButton();
        jLabel = new javax.swing.JLabel();
        dispOrygImgButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setResizable(false);

        jSlider1.setMaximum(255);
        jSlider1.setMinimum(-255);
        jSlider1.setValue(0);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        jSlider1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jSlider1MouseExited(evt);
            }
        });

        rValueTb.setText("0");

        bValueTb.setText("0");

        gValueTb.setText("0");

        addRgbValueButton.setText("Dodaj");
        addRgbValueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRgbValueButtonActionPerformed(evt);
            }
        });

        subtractRgbValueButton.setText("Odejmij");
        subtractRgbValueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtractRgbValueButtonActionPerformed(evt);
            }
        });

        multiplyRgbValueButton.setText("Pomnóż");
        multiplyRgbValueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyRgbValueButtonActionPerformed(evt);
            }
        });

        divideRgbValueButton.setText("Podziel");
        divideRgbValueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideRgbValueButtonActionPerformed(evt);
            }
        });

        jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel.setText("Jasność");
        jLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        dispOrygImgButton.setText("Przywróć oryginalny obraz");
        dispOrygImgButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispOrygImgButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Porównaj obecny obraz z oryginałem");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Wypisz obecnie wysw. pixele do konsoli");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Przejdz do skali szarosci 1");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Przejdz do skali szarości 2");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rValueTb, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(gValueTb, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bValueTb))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(addRgbValueButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(subtractRgbValueButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(multiplyRgbValueButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(divideRgbValueButton)))
                            .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dispOrygImgButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addRgbValueButton)
                    .addComponent(subtractRgbValueButton)
                    .addComponent(multiplyRgbValueButton)
                    .addComponent(divideRgbValueButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rValueTb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gValueTb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bValueTb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dispOrygImgButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addRgbValueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRgbValueButtonActionPerformed
        // TODO add your handling code here:
        blockFrame();
        int r = Integer.parseInt(rValueTb.getText());
        int g = Integer.parseInt(gValueTb.getText());
        int b = Integer.parseInt(bValueTb.getText());
        addRgbValueButton.setEnabled(false);
        imgTransform.transformImage(r, g, b, ilut.getAddLookupTable());
        addRgbValueButton.setEnabled(true);
        unblockFrame();
    }//GEN-LAST:event_addRgbValueButtonActionPerformed

    private void subtractRgbValueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtractRgbValueButtonActionPerformed
        // TODO add your handling code here:
        blockFrame();
        int r = Integer.parseInt(rValueTb.getText());
        int g = Integer.parseInt(gValueTb.getText());
        int b = Integer.parseInt(bValueTb.getText());
        subtractRgbValueButton.setEnabled(false);
        imgTransform.transformImage(r, g, b, ilut.getSubtractLookupTable());
        subtractRgbValueButton.setEnabled(true);
        unblockFrame();
    }//GEN-LAST:event_subtractRgbValueButtonActionPerformed

    private void multiplyRgbValueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyRgbValueButtonActionPerformed
        // TODO add your handling code here:
        blockFrame();
        int r = Integer.parseInt(rValueTb.getText());
        int g = Integer.parseInt(gValueTb.getText());
        int b = Integer.parseInt(bValueTb.getText());
        multiplyRgbValueButton.setEnabled(false);
        imgTransform.transformImage(r, g, b, ilut.getMultiplyLookupTable());
        multiplyRgbValueButton.setEnabled(true);
        unblockFrame();
    }//GEN-LAST:event_multiplyRgbValueButtonActionPerformed

    private void divideRgbValueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideRgbValueButtonActionPerformed
        // TODO add your handling code here:
        blockFrame();
        int r = Integer.parseInt(rValueTb.getText());
        int g = Integer.parseInt(gValueTb.getText());
        int b = Integer.parseInt(bValueTb.getText());
        if (r > 0 && g > 0 && b > 0) {
            divideRgbValueButton.setEnabled(false);
            imgTransform.transformImage(r, g, b, ilut.getDivideLookupTable());
            divideRgbValueButton.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(this, "Nie dzielimy przez 0!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        unblockFrame();
    }//GEN-LAST:event_divideRgbValueButtonActionPerformed

    private void dispOrygImgButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dispOrygImgButtonActionPerformed
        // TODO add your handling code here:
        blockFrame();
        imagePanel.setOryginalImageForDisplay();
        imagePanel.displayImage();
        unblockFrame();
    }//GEN-LAST:event_dispOrygImgButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (imagePanel.comparePixelArrays()) {
            JOptionPane.showMessageDialog(this, "Tablice sa takie same", "Informacja", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Tablice NIE sa takie same", "Informacja", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        blockFrame();
        imagePanel.displayCurrentlyDisplayedPixels();
        unblockFrame();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        // TODO add your handling code here:
        blockFrame();
        int sliderValue = jSlider1.getValue();
        imagePanel.setOryginalImageForDisplay();
        if (sliderValue < 0) {
            imgTransform.transformImage(-sliderValue, -sliderValue, -sliderValue, ilut.getBrightnessLookupTable());
        } else {
            imgTransform.transformImage(sliderValue, sliderValue, sliderValue, ilut.getDarknessLookupTable());
        }
        
        previousSliderValue = sliderValue;
        unblockFrame();
    }//GEN-LAST:event_jSlider1StateChanged

    private void jSlider1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jSlider1MouseExited

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        blockFrame();
        imgTransform.imageToDarkScale();
        unblockFrame();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        blockFrame();
        imgTransform.imageToDarkScale2();
        unblockFrame();
    }//GEN-LAST:event_jButton4ActionPerformed

    //Blocks editPictureFrame
    private void blockFrame() {
        this.setEnabled(false);
    }

    //Unblocks editPictureFrame
    private void unblockFrame() {
        this.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRgbValueButton;
    private javax.swing.JTextField bValueTb;
    private javax.swing.JButton dispOrygImgButton;
    private javax.swing.JButton divideRgbValueButton;
    private javax.swing.JTextField gValueTb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JButton multiplyRgbValueButton;
    private javax.swing.JTextField rValueTb;
    private javax.swing.JButton subtractRgbValueButton;
    // End of variables declaration//GEN-END:variables
}
