/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transformation;

import basicshapes.BasicShapeDrawPanel;
import java.awt.Component;
import java.awt.GridLayout;
import java.awt.Point;
import java.awt.Shape;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Line2D;
import java.awt.geom.Rectangle2D;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JPanel;

/**
 *
 * @author honzik
 */
public class ShapeTransformDrawFrame extends javax.swing.JFrame {

    private JPanel translateComponentsSet;
    private JPanel scaleComponentsSet;
    private JPanel rotateComponentsSet;
    ShapeTransformDrawPanel drawPanel;

    public ShapeTransformDrawFrame() {
        initComponents();
        drawPanel = (ShapeTransformDrawPanel) jPanel3;
        GridLayout gridLayout;

        gridLayout = new GridLayout(2, 2);
        translateComponentsSet = new JPanel(gridLayout);
        translateComponentsSet.add(new JLabel("x:"));
        translateComponentsSet.add(new JTextField());
        translateComponentsSet.add(new JLabel("y:"));
        translateComponentsSet.add(new JTextField());

        gridLayout = new GridLayout(1, 2);
        scaleComponentsSet = new JPanel(gridLayout);
        scaleComponentsSet.add(new JLabel("wsp. skalowania:"));
        scaleComponentsSet.add(new JTextField());

        gridLayout = new GridLayout(1, 2);
        rotateComponentsSet = new JPanel(gridLayout);
        rotateComponentsSet.add(new JLabel("Kat:"));
        rotateComponentsSet.add(new JTextField());

        setOptionsForTransform("Translacja");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new ShapeTransformDrawPanel();
        transformationComboBox = new javax.swing.JComboBox<>();
        transformButton = new javax.swing.JButton();
        transformOptionsPanel = new javax.swing.JPanel();
        clearPanelButton = new javax.swing.JButton();

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.setMaximumSize(null);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
        );

        transformationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Translacja", "Skalowanie", "Obrót" }));
        transformationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transformationComboBoxActionPerformed(evt);
            }
        });

        transformButton.setText("Przekształć");
        transformButton.setMaximumSize(new java.awt.Dimension(5, 5));
        transformButton.setMinimumSize(new java.awt.Dimension(5, 5));
        transformButton.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        transformButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transformButtonActionPerformed(evt);
            }
        });

        transformOptionsPanel.setBackground(new java.awt.Color(255, 255, 255));
        transformOptionsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        transformOptionsPanel.setForeground(new java.awt.Color(255, 0, 204));
        transformOptionsPanel.setMinimumSize(new java.awt.Dimension(10, 10));
        transformOptionsPanel.setLayout(new java.awt.GridLayout(0, 1));

        clearPanelButton.setText("Wyczysc ekran");
        clearPanelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearPanelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(transformationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transformButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clearPanelButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(transformOptionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transformationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transformButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearPanelButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transformOptionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void transformButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transformButtonActionPerformed
        // TODO add your handling code here:
        String transformOption = (String) transformationComboBox.getSelectedItem();
        JPanel transformInputPanel = (JPanel) transformOptionsPanel.getComponent(0);
        Component[] userInputComponents = transformInputPanel.getComponents();
        Transform2D transform2D = new Transform2D(drawPanel);
        SimpleShape simpleShape = drawPanel.getSimpleShape();

        double x = 0, y = 0, scaleValue = 0;
        int angle;
        double centerX = drawPanel.getCenterX();
        double centerY = drawPanel.getCenterY();
        if (transformOption.compareTo("Translacja") == 0) {
            x = Double.parseDouble(((JTextField) userInputComponents[1]).getText());
            y = Double.parseDouble(((JTextField) userInputComponents[3]).getText());
            transform2D.translatePointList(simpleShape.getPointList(), x, -y);
        } else if (transformOption.compareTo("Skalowanie") == 0) {

            scaleValue = Double.parseDouble(((JTextField) userInputComponents[1]).getText());
            transform2D.scalePointList(simpleShape.getPointList(), scaleValue, centerX, centerY);
        } else if (transformOption.compareTo("Obrót") == 0) {
            angle = Integer.parseInt(((JTextField) userInputComponents[1]).getText());
            transform2D.rotatePointList(simpleShape.getPointList(), angle, centerX, centerY);
        }
        drawPanel.repaint();
    }//GEN-LAST:event_transformButtonActionPerformed

    private void transformationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transformationComboBoxActionPerformed
        // TODO add your handling code here:
        String transformOption = (String) transformationComboBox.getSelectedItem();
        setOptionsForTransform(transformOption);
    }//GEN-LAST:event_transformationComboBoxActionPerformed
    
    private void setOptionsForTransform(String shape) {
        transformOptionsPanel.removeAll();
        if (shape.compareTo("Translacja") == 0) {
            transformOptionsPanel.add(translateComponentsSet);
        } else if (shape.compareTo("Skalowanie") == 0) {
            transformOptionsPanel.add(scaleComponentsSet);
        } else if (shape.compareTo("Obrót") == 0) {
            transformOptionsPanel.add(rotateComponentsSet);
        }
        transformOptionsPanel.validate();
        repaint();
    }
    
    private void clearPanelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearPanelButtonActionPerformed
        // TODO add your handling code here:
        drawPanel.getSimpleShape().removePoints();
        drawPanel.repaint();
    }//GEN-LAST:event_clearPanelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearPanelButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton transformButton;
    private javax.swing.JPanel transformOptionsPanel;
    private javax.swing.JComboBox<String> transformationComboBox;
    // End of variables declaration//GEN-END:variables

}
